### ISSUE TITLE
ccminer empty/black screen 

### ISSUE THREAD

**Issue by Citymix** [nemosminer/NemosMiner-v2.2#36]
Hello , I'm having a problem, I have two rigs with 6 GPU's 1080 ti, 
Both are same processor (G4400), 8 GB RAM - but virtual Memory set to 64, and same SSD 120GB. 
My problem is after 2 hours or some time ccminer is lagging (separated cards to 3 each, by opening two start.bat), the ccminer windows gets empty/black screen (and sometimes windows gets freezes) and I have to manually close the program (or force reboot) and reopen it again, this problem happens a lot. 

![20885099_10211975167246223_2078196353_n](https://user-images.githubusercontent.com/30720276/29366148-4735b8d2-82aa-11e7-9b96-18c4cb512231.jpg)

![20904408_10211975311009817_56200750_o](https://user-images.githubusercontent.com/30720276/29366261-97f753e8-82aa-11e7-9c82-ff56e9ef0aad.jpg)

Alexis78 Nist5 benchmark doesnt understand separated 3 GPU's, so I edited benchmarks manually for each 3 GPU's.

Windows 10 Pro 
6 GPU 1080 ti
G4400 Processor 
8GB RAM (virtual memory set to 64GB)
SSD 120GB
3 Power supplies for each rig (1000W) 

I just want to know is it because of that I separate 3 GPU's for each start.bat ?
I'm testing now same rig with one start.bat (6 GPU's), 4 hours of work and still no black screen on ccminer.

And the other rig with 6 GPU's in one start.bat im having benchmark problems with 6 GPUs recognizing problem, you never know how many cards work out of that 6 GPUs.

**Comment by nemosminer** [comment]
its because your running two Instance of NemosMiner at once... 
which should be fine to get the most out of Alexis78 you need to do that with 6card rig.. 

Fix = try copy and pasting NemosMiner Folder run one for each instance and edit: NemosMiner-v2.1 .ps1 find: $WorkerName = "ID=NemosMiner-v2.1    

eg: [String]$WorkerName = "ID=NemosMiner-v2.1/cards123

then do the same for copied folder:

[String]$WorkerName = "ID=NemosMiner-v2.1/456

you may have to use a different wallet address for each instance to.. i don't have any 6 card rigs anymore so can't test for you.. all my Miners a 2-3 1080ti's on one psu no risers much more Reliable...
